### ISSUE TITLE
Seleccionar la plantilla base del sitio web

### ISSUE THREAD

**Issue by Skatox** [mozillavenezuela/mozillavenezuela.org#1]
Para comenzar el desarrollo, tenemos que definir la plantilla base de Wordpress que utilizará el sitio web, la cual seleccionaremos en la próxima reunión.

Así que comenten en este issue las propuestas que posean, no he revisado pero un compañero de Mozilla sugirió usar: https://github.com/Mte90/WP-Mozilla aunque realmente no la he revisado.

**Comment by AlexR1712** [comment]
Buenas, yo recomendaria usar los siguientes temas para usarlos como base, principalmente los primeros 2 de la siguiente lista..
https://wordpress.org/themes/meris/
https://wordpress.org/themes/zerif-lite/
https://shapebootstrap.net/item/1524965-flat-theme-free-responsive-multipurpose-site-template
http://www.fabthemes.com/revera/

Saludos!

**Comment by carloselhalabi** [comment]
¡Flat Theme me gusta mucho! 
Se ve muy personalizable, pero no logré conseguir por ningún lugar bajo qué licencia está distribuido, y además en los comentarios se indica que no existe un tema Wordpress, es sólo una plantilla HTML (creo que de todas formas útil).

**Comment by humberts90** [comment]
Muy buenas tardes a todos muchachos.

Como quedamos en la reunión pasada revise algunos temas disponibles de la comunidad Mozilla y me di cuenta que el tema más utilizado es del estilo de Mozilla Bolivia (http://www.mozillabolivia.org/) o Mozilla Paraguay (http://www.mozillaparaguay.org/) sin embargo no encontré ningún repositorios de estos. Otro tema muy parecido el cual si tiene repo es el de Mozilla Rusia (https://github.com/mozilla-ro/wp-theme) es bastante simple, sin embargo cumple con la tónica de la comunidad si se decide usar un "Estándar". También encontré el repositorio de una evento realizado por Mozilla Brasil (http://womoz.mozillabrasil.org.br/) del cual me gustó el efecto portafolios, pero personalmente no mucho más (https://github.com/mozillabrasil/womoz.mozillabrasil.org.br).

Por ultimo está el de nuestros vecinos Mozilla Colombia que aunque no me animo a modificarlo mucho, tiene un esqueleto también bastante utilizado en la comunidad (https://github.com/jonathanorlando/temaworpress).

Probé el que el compañero Skatox nos compartió en la reunión, pero lo vi muy simple lo único aprovechable es el acordeón de la parte superior el cual lo tienen todos los demás. (https://github.com/Mte90/WP-Mozilla)

No encontré ningún otro de la comunidad que tuviese repositorio, pero me atreví a buscar una plantilla de Wordpress con licencia GPL (la versión gratuita, que no sé si se podría utilizar). Esta es muy personalizable por lo que ví. Pero no encontré documentación para lograr el efecto portafolio que se puede ver en la vista previa (https://wordpress.org/themes/albar/). Por colores, solo sería personalizar y se vería muy bien.

Espero su opinión, estaré revisando por si encuentro algún otro repositorio de la comunidad.

Saludos.

**Comment by humberts90** [comment]
Muy buenas tardes a todos muchachos.

Como quedamos en la reunión pasada revise algunos temas disponibles de la comunidad Mozilla y me di cuenta que el tema más utilizado es del estilo de Mozilla Bolivia (http://www.mozillabolivia.org/) o Mozilla Paraguay (http://www.mozillaparaguay.org/) sin embargo no encontré ningún repositorios de estos. Otro tema muy parecido el cual si tiene repo es el de Mozilla Rusia (https://github.com/mozilla-ro/wp-theme) es bastante simple, sin embargo cumple con la tónica de la comunidad si se decide usar un "Estándar". También encontré el repositorio de una evento realizado por Mozilla Brasil (http://womoz.mozillabrasil.org.br/) del cual me gustó el efecto portafolios, pero personalmente no mucho más (https://github.com/mozillabrasil/womoz.mozillabrasil.org.br).

Por ultimo está el de nuestros vecinos Mozilla Colombia que aunque no me animo a modificarlo mucho, tiene un esqueleto también bastante utilizado en la comunidad (https://github.com/jonathanorlando/temaworpress).

Probé el que el compañero Skatox nos compartió en la reunión, pero lo vi muy simple lo único aprovechable es el acordeón de la parte superior el cual lo tienen todos los demás. (https://github.com/Mte90/WP-Mozilla)

No encontré ningún otro de la comunidad que tuviese repositorio, pero me atreví a buscar una plantilla de Wordpress con licencia GPL (la versión gratuita, que no sé si se podría utilizar). Esta es muy personalizable por lo que ví. Pero no encontré documentación para lograr el efecto portafolio que se puede ver en la vista previa (https://wordpress.org/themes/albar/). Por colores, solo sería personalizar y se vería muy bien.

Creo que en todo caso la idea de hacerlo desde cero no esta mal, pero no sé que opinen los demas.

Espero su opinión, estaré revisando por si encuentro algún otro repositorio de la comunidad.

Saludos.

**Comment by carloselhalabi** [comment]
En lo personal considero que las plantillas del estilo Mozilla sandstone están un poco desactualizadas, y su diseño es viejo (el repo de Moz Colombia es de 2010). Me parece que siguiendo lineamientos y webs más nuevas (y para que sea un cambio notable dentro de la web MozVe) deberíamos buscar algo como lo que Mozilla Cuba [http://firefoxmania.uci.cu] y Mozilla Indonesia [http://mozilla.or.id] han creado. A mi parecer se ve más fresco, más limpio y más 2015+.

**Comment by humberts90** [comment]
Busque algo parecido a la de Mozilla indonesia pero no vi ningún repositorio de la comunidad con ese tema

**Comment by carloselhalabi** [comment]
Hay formas de acercarse a la comunidad para solicitar ayuda. Además, creo que Moz Indonesia está usando un simple stack HTML5/JS/CSS, no Wordpress.

**Comment by Skatox** [comment]
Gracias por la extensa revision @humberts90 eso era lo que se debía hacer, en la próxima reunión decidiremos el tema base a usar, o probablemente hagamos uno propio. Depende de lo escogido en la reunion, sin embargo, sigan compartiendo lo que consigan.

**Comment by oteroweb** [comment]
Bueno muchachos cualquier cosita les puedo colaborar con editar el php del tema o en la creacion del mismo

**Comment by Villanuevand** [comment]
Yo concuerdo con la opinión de @carloselhalabi crei que deberíamos buscar diseños como los de Mozilla Cuba e Indonesia. E integrar lo mejor de otros temas que encontremos para cubrir nuestra necesidad.

**Comment by ThePhoenixBird** [comment]
Añado los repos de 

India: https://github.com/debloper/torch

Irlanda: https://github.com/stejmurphy/mozirelandtheme

**Comment by Skatox** [comment]
Hablando con @humberts90 nos parece bien el tema de Irlanda, al parecer es muy configurable y es el mas actualizado de todos, le faltan unos detalles para mejorar el responsive pero en general está bien.

**Comment by carloselhalabi** [comment]
A mi me pareció mejor el tema de Mozilla India, pero me voy por lo que decida la mayoría. Hagámoslo.

**Comment by Luda16-zz** [comment]
Ambos themes estan muy interesantes! Ahora bien ¿Que metodologia se utilizaria para el desarrollo del site?

**Comment by Skatox** [comment]
Lo de la metodología y selección del tema lo haremos el próximo domingo
a las 2:30 por el canal de IRC, pendientes de la reunión. Por ahora
pueden descargar los temas de mozilla india y mozilla irlanda para que
los pruebas y puedan ayudar a decidir con bases.

**Comment by humberts90** [comment]
Buenos días a todos, como menciona @Skatox el domingo pasado estuvimos viendo ciertas ventajas que podría tener el tema de Mozilla Irlanda compartido por Arturo. Hoy lo estuve revisando nuevamente, me parece que a pesar de ser simple quien lo hizo se tomó el tiempo de hacerlo personalizable, con unos cuantos click se logra las disposición de las áreas rápidamente. Se acomodaría lo que no nos guste y se haría resposive.

en todo caso mas tarde si alguien tiene alguna otra idea la puede exponer por aquí o en la reunión

**Comment by Skatox** [comment]
En la reunión de hoy se decidió usar el tema de mozilla irlanda como base, ya actualmente está instalado en la rama /dev
