### ISSUE TITLE
Nuevo logo para Mozilla Venezuela

### ISSUE THREAD

**Issue by Skatox** [mozillavenezuela/mozillavenezuela.org#2]
Desde hace tiempo se viene decidiendo hacer nuevo logo para la comunidad para facilitar su visualización en la web, impresión en franelas, entre otras cosas.

La idea es tener este logo finalizado para el relanzamiento del sitio web y para faciltar la selección de la paleta de colores, pues ésta deberia estar basda en el logo.

@ThePhoenixBird quedó encargado en comunicarse con el equipo creativo de Mozilla Hispano para desarrollar el logo.

**Comment by ThePhoenixBird** [comment]
Javier Dávalos [ Javfox ] de Mozilla Hispano nos estará asistiendo con esta tarea, ya hace un tiempo atrás se habían hecho unos bocetos pero no los pude encontrar, por lo que espero a que Javier nos vuelva a enviar la información y arrancar de allí.

Nos basaremos en nuestra mascota actual, el guacamayo de fuego para un logotipo mas moderno y de diseño plano, que sea mas fácil de utilizar en diferentes elementos:

![mozillave-workmark](https://cloud.githubusercontent.com/assets/1944169/9986223/bfe79b40-6003-11e5-9827-d70ec9a38573.png)

**Comment by Skatox** [comment]
Cerrando, hace 2 años Karla Hernandez de Mozilla Hispano nos hizo un logo.
