### ISSUE TITLE
Limpiar la rama dev

### ISSUE THREAD

**Issue by Skatox** [mozillavenezuela/mozillavenezuela.org#3]
Actualmente en la rama dev está el tema anterior, el tema clonado de mozilla irlanda y los plugines viejos, la tarea consiste en:
- Eliminar los temas anteriores y sus dependencias (yoko)
- Eliminar los plugines innecesarios o no se si piensan borrar todos y comenzar el desarrollo desde 0.
- Actualizar cualquier información del tema que diga que es Mozilla Irlanda a Venezuela (nombre del tema, descripción, autores, etc), aunque se debe tener comentado en algun lado que el tema es un fork de l original de mozilla irlanda.

**Comment by Luda16-zz** [comment]
¿Algun avance de esto? Podria contribuir en este issue

**Comment by humberts90** [comment]
Hoy me pondré con esto, estuve un poco ocupado, disculpen

**Comment by humberts90** [comment]
y claro @Luda16 puedes colaborar en este issues

**Comment by Skatox** [comment]
Si, todos son bienvenidos en colaborar con esto.

**Comment by humberts90** [comment]
Commit realizado:

Se eliminó el tema hijo de yoko, así como el tema yoco. 
Se eliminaron plugins y se dejaron los que posiblemente se reutilizarian. 
Se cambio la informacion del tema Mozilla Irlanda a Mozilla venezuela y se documento (README del tema) que es un fork del tema One Mozilla Irlanda. 
Por ultimo intenté traducir desde los archivos de lenguaje ciertas cosas del tema (pero aqui necesito ayuda)

**Comment by humberts90** [comment]
Tema asociado a la BD

![theme](https://cloud.githubusercontent.com/assets/3399255/10102646/70d668a6-6369-11e5-8deb-6c189a18c193.PNG)

Definición del tema
![admin-theme](https://cloud.githubusercontent.com/assets/3399255/10102645/70d07414-6369-11e5-9804-bb3182c64fc4.PNG)

Opciones configurables del tema
![admin-theme2](https://cloud.githubusercontent.com/assets/3399255/10102644/70cb79c8-6369-11e5-8126-18eca2a646d2.PNG)

Opciones configurables del tema
![admin-theme3](https://cloud.githubusercontent.com/assets/3399255/10102643/70c7498e-6369-11e5-9ff6-e9d88f0e305d.PNG)

Opciones configurables del tema
![admin-theme4](https://cloud.githubusercontent.com/assets/3399255/10102641/70c042ba-6369-11e5-91b0-036f8b54ddbf.PNG)

Opciones configurables del tema
![admin-theme5](https://cloud.githubusercontent.com/assets/3399255/10102642/70c2cad0-6369-11e5-99bd-9c37a5901d09.PNG)

Imagen responsive movil
![theme-responsive](https://cloud.githubusercontent.com/assets/3399255/10102640/70bf9464-6369-11e5-9e8b-613a63e8017f.PNG)

Imagen responsive table
![theme-responsive2](https://cloud.githubusercontent.com/assets/3399255/10102638/70b31d6a-6369-11e5-86e3-a7293638cd6b.PNG)

Plugins generales
![theme-plugins](https://cloud.githubusercontent.com/assets/3399255/10102639/70b9a536-6369-11e5-8af8-a96a42b43616.PNG)

Sigo diciendo que no es totalmente responsive como indicaron la reunion pasada, hoy en la tarde - noche y mañana intentaré dedicarme a la adaptación de los plugins con Jose Otero @pcimagenca en la adaptación de los plugins.

**Comment by Skatox** [comment]
Estuve revisando y la rama quedó limpia. Con eso es suficiente para empezar
