### ISSUE TITLE
Crear el entrono de desarrollo con vagrant/docker

### ISSUE THREAD

**Issue by Skatox** [mozillavenezuela/mozillavenezuela.org#6]
La idea es tener un entorno de desarrollo con el sitio web en wordpress y la base de datos junta. Se desea implementar esto utilizanado docker o vagrant. 

¿Para ello que datos necesitamos del servidor? @alexsalas @e1th0r ¿Que sería necesario o les hace falta para hacer esto?

**Comment by maedca** [comment]
hola me gustaría que fuese por vagrant, tengo un entorno ya listo para lo mismo;  @Skatox necesitaríamos la base de datos y el wp, pero seria bueno instalar un wp de cero e ir creando allí las modificaciones del site.

**Comment by Skatox** [comment]
Gracias por los comentarios maedca, yo tengo una copia de la BD para desarrollo. En vagrant se necesitaría saber la distribución y versiones del sistema operativo de producción? Sería copiarse de la de MH?

**Comment by maedca** [comment]
Pues no creó que la.versión del sistema operativo influya tanto mas bien la
versión de PHP y MySQL

**Comment by ThePhoenixBird** [comment]
Esos datos se pueden obtener enviando un correo a tecnico@mh

**Comment by Skatox** [comment]
@ThePhoenixBird Excelente, enviado. Apenas respondan colocaré aqui la información.

**Comment by maedca** [comment]
Hola @skatox algún avance sobre esto?

**Comment by Skatox** [comment]
@maedca En este momento me contestó técnico con los datos del servidor, supongo que no los debo publicar por acá. Me pregunto si a la final @e1th0r puede hacer la imagen, si no, la hacemos nosotros.

**Comment by maedca** [comment]
Ok @skatox gracias quedo al pendiente para lo de la maquina vagrant

**Comment by ThePhoenixBird** [comment]
@Skatox puedes enviar a @maedca los datos también, para que tanto el como @e1th0r trabajen en esto y se pueda entonces tener la maquina vagrant lo mas pronto posible.

**Comment by ajsb85** [comment]
Hay que desarrollar un pequeño manual de usuario de la maquina vagrant. Y los requerimientos para desplegarla. Saludos.

**Comment by oteroweb** [comment]
Subo por aqui la VM? a fin que quienes quieran probarla?

**Comment by maedca** [comment]
Si sube por acá la conf

**Comment by oteroweb** [comment]
Esta la estoy probando Pero mi internet esta lento 

El ip de acceso es 10.4.4.58

Breve explicacion, solo son dos archivos 
Vagrant file (con la configuracion de como será la maquina virtual)
linea 23: indica la ruta de acceso privado por ip
linea 51: el script el cual sera ejecutado una vez iniciada la maquina provision.sh

provision.sh tiene todas las instrucciones para la instalacion, una vez pruebe la maquina solo quedan dos lineas que son el importar la base de datos y direccionar esta VM tiene phpmyadmin me indican si es necesario o lo quito 

subiendolo a mega por aqui no me permite subir zip

**Comment by oteroweb** [comment]
https://github.com/pcimagenca/vagrant-Ngix-mysql5.5-phpmyadmin--f

**Comment by oteroweb** [comment]
Ya esta actualizado para que la tabla import.sql se agregue automaticamente al hacer vagrant up el usuario es root y la contraseña es admin, cualquier error me lo notifican
