### ISSUE TITLE
Crear subdominio para pruebas de la rama DEV

### ISSUE THREAD

**Issue by ajsb85** [mozillavenezuela/mozillavenezuela.org#7]
Crear subdominio en MH o cualquier otro Host, con la rama dev y generar acceso a los miembros de la comunidad que quieran colaborar.

**Comment by ThePhoenixBird** [comment]
lo de dar accesos es complicado por temas de seguridad, es mejor que se haga un sitio de pruebas y que este copie cada cierto tiempo la rama dev de git en el.

**Comment by Skatox** [comment]
Estuve teniendo problemas para montarla en mi servidor por versiones, accesos, etc. Creo que no es necesario, pues se pueden bajar la máquina virtual de vagrant de #6 y trabajar/probar en ella de una vez.
